export const SIGNIN_REQUEST = "SIGNIN_REQUEST"
export const SIGNIN_SUCCESS = "SIGNIN_SUCCESS"
export const SIGNIN_FAIL = "SIGNIN_FAIL"

export const GET_SIGNIN_REQUEST = "GET_SIGNIN_REQUEST"
export const GET_SIGNIN_SUCCESS = "GET_SIGNIN_SUCCESS"
export const GET_SIGNIN_FAIL = "GET_SIGNIN_FAIL"


