export { default as Home } from "./Home"
export { default as Table } from "./Table"
export { default as Testinomial } from "./Testinomial"
export { default as Register } from "./Register"
export { default as Login } from "./Login"